package administrador;
import Config.ConfigMain;
import Login.*;
import javax.swing.JOptionPane;

public class PagosNuevos extends javax.swing.JFrame {

    public PagosNuevos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btmPacientes = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btmHistorialPagos = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btmPagos = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btmRegistroMedicOtros = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnPagar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxResutado = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreDueno = new javax.swing.JTextField();
        txtNombreMascota = new javax.swing.JTextField();
        txtPesoM = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btmTipTratamiento = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btmBorrar = new javax.swing.JButton();
        txtEdadMascota = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtEspecieM = new javax.swing.JTextField();
        btmOkPagos = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtGenero = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        boxPrescripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtCerrarSeccion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/imagen.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 80, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre de usuario");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, 27));

        jPanel4.setBackground(new java.awt.Color(138, 209, 132));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        btmPacientes.setBackground(new java.awt.Color(255, 255, 255));
        btmPacientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmPacientes.setText("reservas del paciente");
        btmPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmPacientesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 153));

        btmHistorialPagos.setBackground(new java.awt.Color(255, 255, 255));
        btmHistorialPagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmHistorialPagos.setText("historial de pagos");
        btmHistorialPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmHistorialPagosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmHistorialPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmHistorialPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 153));

        btmPagos.setBackground(new java.awt.Color(255, 255, 255));
        btmPagos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmPagos.setText("nuevos pagos");
        btmPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmPagosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmPagos, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmPagos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 153));

        btmRegistroMedicOtros.setBackground(new java.awt.Color(255, 255, 255));
        btmRegistroMedicOtros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btmRegistroMedicOtros.setText("registro de medicamentos y productos");
        btmRegistroMedicOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btmRegistroMedicOtrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmRegistroMedicOtros, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btmRegistroMedicOtros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 153, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        jPanel9.add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, 30));

        boxResutado.setColumns(20);
        boxResutado.setLineWrap(true);
        boxResutado.setRows(5);
        boxResutado.setWrapStyleWord(true);
        boxResutado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reseta medica del Paciente:", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jScrollPane1.setViewportView(boxResutado);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 277, 410));

        jLabel5.setText("Nombre del paciente:");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setText("Nombre del Dueño");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        txtNombreDueno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDuenoActionPerformed(evt);
            }
        });
        jPanel9.add(txtNombreDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 22, 150, 30));
        jPanel9.add(txtNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 62, 150, 30));
        jPanel9.add(txtPesoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 142, 150, 30));

        jLabel7.setText("Peso del paciente:");
        jPanel9.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btmTipTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pastillas", "Inyeccion", "Medicamentos" }));
        jPanel9.add(btmTipTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 150, 30));

        jLabel8.setText("Genero  del paciente:");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 20));

        btmBorrar.setText("Borrar");
        btmBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmBorrarActionPerformed(evt);
            }
        });
        jPanel9.add(btmBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, 30));
        jPanel9.add(txtEdadMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 70, 30));

        jLabel9.setText("Edad del paciente:");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel11.setText("Especie del paciente:");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel9.add(txtEspecieM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 150, 30));

        btmOkPagos.setText("Agregar");
        btmOkPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmOkPagosActionPerformed(evt);
            }
        });
        jPanel9.add(btmOkPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, 30));

        jLabel12.setText("Años");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 30, 30));

        jLabel13.setText("Kg");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 20, 20));

        jLabel14.setText("Tipo de tratamiento:");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel9.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 150, 30));

        boxPrescripcion.setColumns(20);
        boxPrescripcion.setLineWrap(true);
        boxPrescripcion.setRows(5);
        boxPrescripcion.setWrapStyleWord(true);
        boxPrescripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prescripcion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jScrollPane2.setViewportView(boxPrescripcion);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 250, 120));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 500));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Veterinaria Pet Happy");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/img2.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Config.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BtCerrarSeccion.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BtCerrarSeccion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BtCerrarSeccion.setText("Cerrar Seccion");
        BtCerrarSeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtCerrarSeccionMouseClicked(evt);
            }
        });
        jPanel3.add(BtCerrarSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmPacientesMouseClicked
    ReservaPacientes a1=new ReservaPacientes();
    a1.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btmPacientesMouseClicked

    private void btmRegistroMedicOtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmRegistroMedicOtrosMouseClicked
    RegistroMedicamentosOtros a2=new RegistroMedicamentosOtros();
    a2.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btmRegistroMedicOtrosMouseClicked

    private void btmPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmPagosMouseClicked
    PagosNuevos a3=new PagosNuevos();
    a3.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btmPagosMouseClicked

    private void btmHistorialPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btmHistorialPagosMouseClicked
    HistorialPagos a4=new HistorialPagos();
    a4.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btmHistorialPagosMouseClicked

    private void BtCerrarSeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtCerrarSeccionMouseClicked
        LoginInicio comienzo = new LoginInicio();
        comienzo.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_BtCerrarSeccionMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        ConfigMain Configuracion =new ConfigMain();
        Configuracion.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txtNombreDuenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDuenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDuenoActionPerformed

    private void btmOkPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmOkPagosActionPerformed
        Trascribir();
    }//GEN-LAST:event_btmOkPagosActionPerformed

    private void btmBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmBorrarActionPerformed
        borrar();
    }//GEN-LAST:event_btmBorrarActionPerformed

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        pago();
    }//GEN-LAST:event_btnPagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosNuevos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagosNuevos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtCerrarSeccion;
    private javax.swing.JTextArea boxPrescripcion;
    private javax.swing.JTextArea boxResutado;
    private javax.swing.JButton btmBorrar;
    private javax.swing.JLabel btmHistorialPagos;
    private javax.swing.JButton btmOkPagos;
    private javax.swing.JLabel btmPacientes;
    private javax.swing.JLabel btmPagos;
    private javax.swing.JLabel btmRegistroMedicOtros;
    private javax.swing.JComboBox<String> btmTipTratamiento;
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtEdadMascota;
    private javax.swing.JTextField txtEspecieM;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtNombreDueno;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtPesoM;
    // End of variables declaration//GEN-END:variables

    
    String vacio="";
    private void Trascribir() {
        boxResutado.setText(vacio);
        String NombreD,NombreM, edadM, pesoM, especieM, generoM, tratamiento,Detalles;
        
        NombreD= txtNombreDueno.getText();
        NombreM=txtNombreMascota.getText();
        edadM=txtEdadMascota.getText();
        pesoM= txtPesoM.getText();
        especieM=txtEspecieM.getText();
        generoM=txtGenero.getText();
        tratamiento=btmTipTratamiento.getSelectedItem().toString();
        Detalles=boxPrescripcion.getText();
        boxResutado.append("------------------------------------------------ \n");
        
        boxResutado.append("Nombre del dueño: ");
        boxResutado.append(NombreD+"\n");
        //----------------------------------------------
        boxResutado.append("Nombre del paciente: ");
        boxResutado.append(NombreM+"\n");
        //----------------------------------------------
        boxResutado.append("Edad del paciente: ");
        boxResutado.append(edadM+" años\n");
        //----------------------------------------------
        boxResutado.append("peso del paciente: ");
        boxResutado.append(pesoM+"kg \n");
        //----------------------------------------------
        boxResutado.append("especie del paciente: ");
        boxResutado.append(especieM+"\n");
        //----------------------------------------------
        boxResutado.append("Genero del paciente: ");
        boxResutado.append(generoM+"\n");
        //----------------------------------------------
        boxResutado.append("Tipo de tratamiento: ");
        boxResutado.append(tratamiento+"\n");
        
        boxResutado.append("------------------------------------------------ \n");
        boxResutado.append(Detalles+"\n");
        boxResutado.append("------------------------------------------------ \n");
        
    }

    private void borrar() {
        txtNombreDueno.setText(vacio);
        txtEdadMascota.setText(vacio);
        txtEspecieM.setText(vacio);
        txtGenero.setText(vacio);
        txtNombreMascota.setText(vacio);
        txtPesoM.setText(vacio);
        boxPrescripcion.setText(vacio);
        boxResutado.setText(vacio);
    }

    private void pago() {
        PagoFormaDePago a1= new PagoFormaDePago();
        a1.setVisible(true);
        this.setVisible(false);
        
    }
}
